### ISSUE TITLE
updating \coordinator macro

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/lab-manual#115]
https://github.com/ContextLab/lab-manual/blob/aa8811b4ca3dc10314e1dfa875e36dd548d7c50f/lab_manual.tex#L163

I'll no longer be lab manager as of September 1st (😢 ) and normally we would update `\coordinator` to whomever was taking over that position. But seeing as we're not planning to have a full-time lab manager for the coming year, what should become of it?  We could get rid of it altogether and replace each use of it with `\director`.  Or we could simply update it to point to `\director` and patch the few places where the two appear together for things to make sense, e.g.: https://github.com/ContextLab/lab-manual/blob/aa8811b4ca3dc10314e1dfa875e36dd548d7c50f/lab_manual.tex#L215
Or we could do something different entirely.

**Comment by jeremymanning** [comment]
yeah, i've been thinking about this too-- let's replace the use with \director and then patch the places where they appear together.  are you up for taking care of that @paxtonfitzpatrick (while you're still our lab manager 😄!)

**Comment by paxtonfitzpatrick** [comment]
Yep! I'll take care of it 🙂
