### ISSUE TITLE
Ordering checklist to-do items or supplementing with Trello

### ISSUE THREAD

**Issue by mbluestone** [ContextLab/lab-manual#32]
It's definitely not necessary but it could be helpful to order the new lab member checklist such that items that must be completed prior to completing other items appear earlier in the checklist (e.g. creating a GitHub account would come before submitting a pull request for the lab manual on Github)

Another option is to create a Trello board with an ordered checklist for new lab members that contains necessary information and links to get set up in the lab. This could also serve as a nice introduction to Trello.

**Comment by paxtonfitzpatrick** [comment]
implemented
