### ISSUE TITLE
adding various dartmouth ethics contact information

### ISSUE THREAD

**Issue by guidodarezzo** [ContextLab/lab-manual#66]
- [x] Dartmouth Compliance and Ethics Hotline

- [x] Dartmouth College Misconduct Policy

- [x] Whatever else others suggest/I dig up in my orientation manuals/emails/etc.

**Comment by paxtonfitzpatrick** [comment]
hey @guidodarezzo, are you still interested in adding things like this? (I added the Compliance and Ethics Hotline and we link to Dartmouth's Title IX policies).  If not, can you go ahead and close this?

**Comment by guidodarezzo** [comment]
@paxtonfitzpatrick I added these awhile back! Closing now.
