### ISSUE TITLE
Added clarification to CITI registration

### ISSUE THREAD

**Issue by austinzhang1018** [ContextLab/lab-manual#73]
I thought it might be helpful to add Human Subjects Research explicitly as the training field within the instructions for CITI registration.

**Comment by lucalit888** [comment]
This a great clarification! Adding some instructions (on page 20 of the lab manual) to select the "Human Subjects Research - Basic Courses" training option would be helpful.

**Comment by paxtonfitzpatrick** [comment]
fixed
