### ISSUE TITLE
CITI registration instructions & Google Calendar Notifications 

### ISSUE THREAD

**Issue by lucalit888** [ContextLab/lab-manual#74]
On page 20 of the lab manual, an extra instruction can be added to clarify that the training option we select is "Human Subjects Research - Basic Courses". 

In addition, on page 22, optional instructions can be provided on how to turn Chrome notifications ON for Google Calendar, which may be helpful for better reminding team members of calendar updates.

**Comment by paxtonfitzpatrick** [comment]
CITI course clarification added.

I think instructions on Chrome notifications are a bit outside the scope of the lab manual (though not a bad idea to have them on!)
