### ISSUE TITLE
Typo and Broken Links

### ISSUE THREAD

**Issue by ghan314** [ContextLab/lab-manual#76]
On Page 19, task 2, the word "cheatsheet" should be two words--"cheat sheet." Also, the links for "Github cheatsheet" and "Github workflow" gave 404 errors, so I updated the links. 

e.g. -- the "Github cheatsheet" link used to be: https://github.com/ContextLab/lab-manual/tree/master/resources/git-cheatsheet.pdf
I made a pull request to change it to: https://github.com/ContextLab/lab-manual/blob/master/resources/cheatsheets/git-cheatsheet.pdf

**Comment by paxtonfitzpatrick** [comment]
fixed
