### ISSUE TITLE
Onboarding tutorial or instructions?

### ISSUE THREAD

**Issue by jeremymanning** [ContextLab/lab-manual#8]
We could define a set of quick tasks that require learning a set of skills deemed necessary for daily function in the lab.  E.g. it could be something like:
- Run yourself in one of our active experiments (list maintained on SONA?  by lab manager?)
- Create a Jupyter notebook and do a simple analysis
- Compile a PDF document with some bibtex references defined in memlab.bib and including a figure from the simple analysis
- Send results along with signed page for quality check

**Comment by paxtonfitzpatrick** [comment]
Implemented.  Closing!
