### ISSUE TITLE
Typos on pages 13, 14, and 22

### ISSUE THREAD

**Issue by esmechen** [ContextLab/lab-manual#83]
Pg. 13: Added a period to the end of the first bullet under #12
Pg. 14: Capitalized "review" in the first task
Pg. 22: Capitalized "email" in the first task

Perhaps something to consider addressing on page 18 under #1: What if a lab member has class during the all-lab meetings on Tuesdays at 12 pm?

**Comment by paxtonfitzpatrick** [comment]
fixed
