### ISSUE TITLE
pg 26 Suggestion

### ISSUE THREAD

**Issue by cjun357** [ContextLab/lab-manual#89]
According to my understanding of the way the section under computers is written, it seems to indicate that computers that can be loaned to students are owned by the lab. Perhaps we could include other places from which students could try to borrow computers if needed as well ie https://kb.thayer.dartmouth.edu/article/263-loaner-laptops.

**Comment by jeremymanning** [comment]
Most lab computers are loaned to head students, postdocs, and staff.  Undergrads are required to have their own computers to enroll at Dartmouth, so undergrads will usually use their personal computers to do non-compute-intensive lab work.  The exception is if some specialty system is needed, in which case we deal with that on a case-by-case basis.  And all intensive computing can be done on our cluster, which all lab members have access to.
