### ISSUE TITLE
Fate of "Ask a question, answer a question" chapter

### ISSUE THREAD

**Issue by paxtonfitzpatrick** [ContextLab/lab-manual#95]
I think this chapter should probably be removed from the lab manual, and the parts of it worth keeping moved to a different chapter or split off into their own section.  

The chapter currently consists of two `\newthought`s: *Common problems and solutions* and *Who to go to with questions*.

#### Common problems and solutions
This was originally meant to be a repository of frequently encountered lab-related issues and solutions, built up by lab members adding issues or solutions when they came across them.  However, it's never really been used since there are far simpler outlets for asking questions (computrons Slack channel) and documenting fixes (Cacher) that don't involve writing them up in LaTeX and submitting a pull request each time.  I think we should add the three problems/solutions listed to Cacher and nix this entirely.

#### Who to go to with questions
This should definitely stay, since it contains useful information, resources, and links.  I appending it to the previous chapter ("Official lab practices and policies") would fit just fine.  Or, alternatively, it could become an entirely separate chapter.

**Comment by jeremymanning** [comment]
Sounds like a good plan-- let's go with both of your suggestions!
